version: "3"
services:

  php:
    image: wodby/php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      COLUMNS: 160
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres

  php-task-processor:
    build:
      context: ./docker/php-task-processor
      dockerfile: Docker
    depends_on:
      - postgres
    volumes:
      - .:/var/www/html

  postgres:
    image: wodby/postgres:$POSTGRES_TAG
    container_name: "${PROJECT_NAME}_postgres"
    stop_grace_period: 30s
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
